resolve segment name
FormFast/simple-hl7 pull request #1
Opened 2020-06-02 17:57 UTC by splowman-FormFast

2020-06-05 18:55 UTC, rholzum-formfast approved these changes

2020-06-09 18:13 UTC, bpetty-formfast approved these changes

2020-06-09 18:16 UTC, bpetty-formfast requested changes
I am concerned about the .travic.yml.
Do we need to remove that?  That is using the dude's keys to publish to his npm package?

2020-06-10 15:47 UTC, bpetty-formfast approved these changes

2020-06-10 16:04 UTC, merged